spring:
# 默认使用配置dev
  profiles:
    active: dev
  main: 
    banner-mode: "off"
#  关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: false
# 访问端口和上下文路径配置，默认port为80，context-path为空
server:
  port: 82
  servlet:
    context-path: /blog-web
    
mybatis:
#Mapper.xml所在的位置,mapperLocations指的路径是src/main/resources
  mapperLocations: classpath*:/mybatis/mapper/**/*.xml
  configLocation: classpath:conf/mybatis/mybatis-config.xml

#分页插件
pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql

#日志配置
logging:
  # 显示SQL
  level:
    com:
      aboutsai: info  
    org:
      springframework:
        web: info
        transaction: info
      mybatis: info
