spring:
# 默认使用配置dev
  profiles:
    active: dev
  main: 
    banner-mode: "off"
#  关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: false
# 访问端口和上下文路径配置，默认port为80，context-path为空
server:
  port: 80
  servlet:
    context-path: /
    
mybatis:
#entity扫描的包名
  typeAliasesPackage: com.aboutsai.blog.entity
#Mapper.xml所在的位置,mapperLocations指的路径是src/main/resources
  mapperLocations: classpath*:/mybatis/mapper/**/*.xml

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: countSql

#日志配置
logging:
  # 显示SQL
  level:
    com:
      aboutsai: debug  
    org:
      springframework:
        web: info
        transaction: info
      mybatis: info
